name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/sq6fdd7bw6a2kj4gqd4b5/e5852e66-350d-11f1-ba79-8cc681729146.zip?rlkey=9iw54mtlj012o7mnlrybm7gq0&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project quicktest.xcodeproj -scheme 'quicktest' -archivePath quicktest.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv quicktest.xcarchive/Products/Applications/quicktest.app Payload/quicktest.app

          zip -r "quicktest.ipa" "Payload"

          mv quicktest.ipa ${{ runner.temp }}/quicktest.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: quicktest
          path: ${{ runner.temp }}/quicktest.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3