name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/3rremnmcwdx8a1e8luk2h/98c6ec99-352b-11f1-8f18-8cc681729146.zip?rlkey=ur426z9c5uhvhoabkg0gw5tns&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project engine_re_6aios.xcodeproj -scheme 'engine_re_6aios' -archivePath engine_re_6aios.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv engine_re_6aios.xcarchive/Products/Applications/engine_re_6aios.app Payload/engine_re_6aios.app

          zip -r "engine_re_6aios.ipa" "Payload"

          mv engine_re_6aios.ipa ${{ runner.temp }}/engine_re_6aios.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: engine_re_6aios
          path: ${{ runner.temp }}/engine_re_6aios.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3